---
# tasks file for nova compute

# Install
- name: Install OpenStack compute node packages.
  yum: name={{ item }} state=latest
  with_items:
    - centos-release-ovirt36
    - centos-release-qemu-ev
    - openstack-nova-compute
    - sysfsutils

- name: Check not support hardware acceleration.
  shell: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: result
  run_once: True
  ignore_errors: True

- name: Deploy nova configuration files from templates
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
    - { src: 'nova/nova.conf.j2', dest: '/etc/nova/nova.conf' }
    - { src: 'nova/nova-api-paste.ini.j2', dest: '/etc/nova/nova-api-paste.ini'}
  notify: restart nova
  when: not "{{ openstack_all_in }}"

- name: Configure libvirt to use QEMU instead of KVM
  when: result | failed
  lineinfile: >
    dest='/etc/nova/nova.conf'
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^#?virt_type', line: "virt_type = qemu" }

- name: Configure compute node in nova.conf
  lineinfile: >
    dest='/etc/nova/nova.conf'
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^#?novncproxy_base_url', line: "novncproxy_base_url = http://{{openstack_controller_ip}}:6080/vnc_auto.html" }

- name: Ensure nova service is started and enabled on boot.
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - libvirtd
    - openstack-nova-compute