---
# tasks file for nova compute

# Install
- name: Install OpenStack nova packages.
  yum: name={{ item }} state=latest
  with_items:
    - openstack-nova-compute
    - sysfsutils

# Configure
- name: Deploy nova configuration files from templates
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
    - { src: 'nova.conf.j2', dest: '/etc/nova/nova.conf' }
  notify: restart nova


- name: Check not support hardware acceleration.
  shell: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: result
  run_once: True
  ignore_errors: True

- name: Configure libvirt to use QEMU instead of KVM
  when: result | failed
  lineinfile: >
    dest='/etc/nova/nova.conf'
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: "^#?virt_type", line: "virt_type = qemu" }


- name: Install network components
  yum: name={{ item }} state=installed
  with_items:
     - openstack-neutron
     - openstack-neutron-linuxbridge
     - ebtables
     - ipset

- name: Ensure nova service is started and enabled on boot.
  service: name={{ item }} enabled=yes state=started
  with_items:
    - libvirtd
    - openstack-nova-compute
