---
- name: Configure firewall.
  shell: |
    iptables -I INPUT -p tcp -m multiport --ports 5000 -m comment --comment "openstack keystone" -j ACCEPT
    iptables -I INPUT -p tcp -m multiport --ports 8773,8774,8775,6080 -m comment --comment "openstack nova" -j ACCEPT
    iptables -I INPUT -p tcp -m multiport --ports 9696 -m comment --comment "openstack neutron" -j ACCEPT
    iptables -I INPUT -p tcp -m multiport --ports 8000,8004 -m comment --comment "openstack heat" -j ACCEPT
    iptables -A INPUT -s {{ openstack_cidr }}  -p tcp  -m multiport --dports 5672,5671      -j ACCEPT
    iptables -A INPUT -s {{ openstack_controller_ip }}   -p tcp  -m multiport --dports 4369,25672     -j ACCEPT
    iptables -A INPUT -j LOG
    iptables-save > /etc/sysconfig/iptables
  tags: firewall

- name: Restart iptables.
  service: name=iptables state=restarted