---
# configure the host name and add compute and controller hosts to /etc/hosts
- name: Set hostame to "{{ openstack_compute_node_host }}"
  shell: hostnamectl set-hostname "{{ openstack_compute_node_host }}"
  ignore_errors: True

- name: Test {{ openstack_compute_node_host }} exist
  shell: grep "^{{ openstack_compute_node_ip }}" /etc/hosts
  register: test_exits

- name: Append "{{ openstack_compute_node_host }}" to hosts file
  when: test_exits.stdout != ""
  lineinfile: dest=/etc/hosts
              backup=True
              backrefs=True
              state=present
              regexp='(^{{ openstack_compute_node_ip }}(\s+(?! {{ openstack_compute_node_ip }})[\w=/\-\.]+)*)\s*$'
              line='\1 {{ openstack_compute_node_host }}'

# improve the next to tasks
- name: Add "{{ openstack_compute_node_ip }}" to hosts file
  when: test_exits.stdout == ""
  shell: echo "{{ openstack_compute_node_ip }} {{ openstack_compute_node_host }}" >> /etc/hosts

- name: Add "{{ openstack_controller_host }}" to hosts file
  when: '"{{ openstack_controller_ip }} != {{ openstack_compute_node_ip }}"'
  shell: echo "{{ openstack_controller_ip }} {{ openstack_controller_host }}" >> /etc/hosts
