---
# tasks file for ansible-role-nova-compute-node
# Prepare deployment
- include: pre-deploy.yml
  when: not "{{ openstack_all_in }}"

- include: host-config.yml
  when: not "{{ openstack_all_in }}"

# nova
- include: compute_node.yml

# neutron
- include: neutron.yml

#
- include: firewall.yml
  when: not "{{ openstack_all_in }}"