---
# tasks file for ansible-role-nova-compute-node
# Prepare deployment
#- include: pre-deploy.yml

#- include: host-config.yml

# nova
- include: compute_node.yml

# neutron
- include: neutron.yml

#
- include: firewall.yml