---
# Pre deployment tasks

- name: Install required packages
  yum: name="{{ item }}" state=latest
  with_items:
    - iptables
    - iptables-services

- name: Install yum-plugin-priorities and epel-release
  yum: name="{{ item }}" state=latest
  with_items:
    - epel-release

- name: Install Openstack "{{ openstack_version | default(liberty) }}"  packages
  yum: name="{{ item }}" state=latest
  with_items:
    - centos-release-openstack-{{ openstack_version | default(liberty) }}


