---
# Pre deployment tasks



- name: Install yum-plugin-priorities and epel-release
  yum: name="{{ item }}" state=latest
  with_items:
    - epel-release
    - yum-plugin-priorities

- name: Install Openstack "{{ openstack_version | default(liberty) }}"  packages
  yum: name="{{ item }}" state=latest update_cache=yes
  with_items:
    - centos-release-openstack-{{ openstack_version | default(liberty) }}